#! /usr/bin/env python
# capitalize each word in a sentence.

str1 = raw_input().strip()
str1 = str1 + " "
for i in range(0,len(str1)):
 if str1[i-1] == ' ':
  str1 = str1[:i] + str1[i].upper() + str1[i+1:]
print str1
