#! /usr/bin/env python
# To print all co-ordinates of cuboid whose sum is less than N.

X = int(raw_input().strip())
Y = int(raw_input().strip())
Z = int(raw_input().strip())
N = int(raw_input().strip())

l1 = []
for i in range(0, X+1):
 for j in range(0, Y+1):
  for k in range(0, Z+1):
   if (i + j + k) != N:
    l1.append([i, j, k])
print l1
