#! /usr/bin/env python
# Counting all substrings starting with vowel and consonants.
# And declaring winner accordingly (Vowels:Kevin, Consonants:Stuart)

def count(str1, sub):
 if str1.find(sub) == -1:
  return 0
 pos = str1.find(sub)
 return count(str1[pos+1:], sub) + 1

str1 = raw_input().strip()
vowels = ['a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U']
subs_dict = []
vow, con = 0, 0
for i in range(len(str1)):
 for j in range(i, len(str1)):
  substring = str1[i:j+1]
  if substring not in subs_dict:
   subs_dict.append(substring)
   if substring.isalpha():
    if (substring[0] in vowels):
     vow += count(str1, substring)
    else:
     con += count(str1, substring)
if vow > con:
 print "Kevin %s" % vow
elif con > vow:
 print "Stuart %s" % con
else:
 print "Draw"

